/**
 * Копирует макеты из photo/ в client/public/images (и server/public при сборке).
 * Запускайте после замены photo/1.png или photo/2.png: npm run sync:photos
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

const pairs = [
  ['photo/1.png', 'landing-bg.png'],
  ['photo/2.png', 'login-bg.png'],
];

const targets = ['client/public/images'];
if (fs.existsSync(path.join(root, 'server', 'public', 'images'))) {
  targets.push('server/public/images');
}

let version = 0;

for (const [srcRel, name] of pairs) {
  const src = path.join(root, srcRel);
  if (!fs.existsSync(src)) {
    console.warn(`skip: ${srcRel} not found`);
    continue;
  }
  const stat = fs.statSync(src);
  const mtime = stat.mtimeMs ?? stat.mtime.getTime();
  version = Math.max(version, mtime);

  for (const dir of targets) {
    const destDir = path.join(root, dir);
    fs.mkdirSync(destDir, { recursive: true });
    const dest = path.join(destDir, name);
    fs.copyFileSync(src, dest);
    console.log(`copied ${srcRel} -> ${path.relative(root, dest)}`);
  }
}

const outDir = path.join(root, 'client', 'src', 'generated');
fs.mkdirSync(outDir, { recursive: true });
const assetFile = path.join(outDir, 'imageVersions.ts');
fs.writeFileSync(
  assetFile,
  `/** Auto-generated by npm run sync:photos — do not edit */\nexport const imageVersions = {\n  landingBg: '${Math.round(version)}',\n  loginBg: '${Math.round(version)}',\n} as const;\n`,
  'utf8'
);
console.log(`wrote ${path.relative(root, assetFile)} (v=${Math.round(version)})`);
